### ISSUE TITLE
use NuGet PackageReferences by default for Bolero.Templates

### ISSUE THREAD

**Issue by ctaggart** [fsbolero/Template#10]
When getting started at https://fsbolero.io/ `dotnet new -i Bolero.Templates` creates a project that requires `paket`. I don't use paket any more and strongly prefer working with the build in NuGet package references. It supports transitive dependencies. It supports locking with the latest version as well. It works better with other dotnet tooling like `dotnet publish` and friends.

I'm creating this issue because I'm not the only one that hit this stumbling block: https://fsharp.slack.com/archives/C10DLSHQV/p1557920194474300

Although I'd prefer to see this project use NuGet packages as well, this request is for the templates, not quite the same as https://github.com/fsbolero/Bolero/pull/43 .

**Comment by Tarmil** [comment]
(Moving the issue to the Template repo)

For the template, I've now come to agree that it should use plain NuGet by default. Especially now that, for people who prefer Paket, @thinkbeforecoding's `paket.install` makes the conversion pretty painless, you just need to run:

```
paket.install && .paket/paket convert-from-nuget --force
```

We could provide a `--paket` option that would run the above as a post-create script (using a locally installed paket.install ofc).

**Comment by ctaggart** [comment]
Just saw https://twitter.com/fsbolero/status/1134103050149355520 with Bolero 0.5 released! 

Looks like this was fixed by https://github.com/fsbolero/Template/commit/2e59b9c83ecb2199d865d8938000fa52f9357efe

Nice, `dotnet new bolero-app` produced this for the client:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Main.fs" />
    <Compile Include="Startup.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Bolero" Version="0.5.28-preview*" />
    <PackageReference Include="Bolero.Build" Version="0.5.28-preview*" />
    <PackageReference Include="Bolero.HotReload" Version="0.5.28-preview*" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0-preview5-*" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0-preview5-*" />
  </ItemGroup>
</Project>
```

And this for the server:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Startup.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ShinyToy.Client\ShinyToy.Client.fsproj" />
    <PackageReference Include="Bolero.Server" Version="0.5.28-preview*" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Server" Version="3.0-preview5-*" />
  </ItemGroup>
</Project>
```
