### ISSUE TITLE
rzc discover exited with code 1.

### ISSUE THREAD

**Issue by timeshift92** [fsbolero/Template#11]
how to fix?

**Comment by timeshift92** [comment]
fixed dotnet new globaljson --sdk-version 2.1.403

**Comment by StanislavPrusac** [comment]
In my case I solved this error: "rzc discover exited with code 1.", by turning of "Real-time protection" in in Windows Security.
I exclude "dotnet.exe" from "Windows Defender Antivirus" scan and/or allow it through "Controlled folder access".
