### ISSUE TITLE
Option --paket needs documenting

### ISSUE THREAD

**Issue by BentTranberg** [fsbolero/Template#13]
The template for Bolero 0.5 uses NuGet by default, but still supports Paket through the `--paket` option. (https://forums.websharper.com/blog/86911)

The `--paket` option is not yet documented in this repo's README.md

The `--paket` option is not yet documented on page https://fsbolero.io/docs/

**Comment by laenas** [comment]
@Tarmil @BentTranberg 
Just checking - is there anything left to do here?  
README.md references `--paket` and the documentation links to this repo with regards to customizing the template.

**Comment by Tarmil** [comment]
I think we're all good here.
