### ISSUE TITLE
--server=false results in mismatch

### ISSUE THREAD

**Issue by IvanTheGeek** [fsbolero/Template#21]
If the template switch -s=false or --server=false like: 
dotnet new bolero-app -o BoleroNoServer -s=false
is used, the resulting solution still has the project files for the .Server in the folder. 

The Server project is not in the .sln file, so it does not show in VS. 

The Client Main.fs file also contains: 
#if DEBUG
        |> Program.withHotReload
#endif

and the Book Service items as well.

**Comment by zakaluka** [comment]
I just noticed the same thing when testing some PWA-related items.  Adding the ability to enabled/disable remoting (as part of `dotnet new`) may be helpful in preventing the server from being created.

**Comment by Tarmil** [comment]
So, this switch is supposed to only have an effect when combined with `--minimal=true`, because the full template uses remoting. So we should either fix the fact that the project is still removed from the solution with `-s=true -m=false`, or implement a proper remote-less version of the full template.

**Comment by zakaluka** [comment]
Would the simpler solution be to make that clear in the help text and the documentation?

**Comment by Tarmil** [comment]
They do both say that the server flag is ignored if minimal=false. I'm open to a better wording though!

**Comment by zakaluka** [comment]
What may help is a better description of what a 'minimal' application is
and what features are provided when it is set to 'true' or 'false'.  Same
for the 'server' option.

This may be documented somewhere (I was not really able to find it), but I
didn't properly understand what it meant until I created multiple separate
projects and saw the differences in the files themselves (running the
initial applications helped a lot).  I didn't expect the initial
application code to change completely from a counter + book service to a
hello world screen.

Even a small table showing what demos and/or services are created for the
different options (t/t, t/f, f/t, etc.) may address the original concern.
Also, the fact that we almost have "cascading" options (hotreload depends
on server or html, server and html depend on minimal) make it harder to
understand what the end result will be given a particular combination of
parameters.

**Comment by Tarmil** [comment]
The dotnet project template has been modified and now accepts the server=false minimal=false combination (by replacing the remote calls with requests to a static JSON file).
