### ISSUE TITLE
Version 0.14.13 does not seem to work

### ISSUE THREAD

**Issue by AlexBoehm** [fsbolero/Template#25]
When I create a new project with  from version 0.14.13 of Bolero.Templates the project is not working. I get the error below:

![image](https://user-images.githubusercontent.com/4753505/87519860-776e8000-c682-11ea-8dd2-99cda32746e8.png)

I reverted the templates back to Version 0.13.6. This is working fine.

**Comment by rbrus** [comment]
This is related to: https://github.com/fsbolero/Bolero/issues/133

**Comment by Tarmil** [comment]
Right. In the 0.14 template, I replaced the strict dependency versions with `3.2.*`, so if the new 3.2.1 package causes problems, then that explains why the new template has these problems.

**Comment by Tarmil** [comment]
I think I've found the culprit. The linker in Microsoft.AspNetCore.Components.WebAssembly.Build 3.2.1 over-eagerly removes System.Threading.dll and causes the issue. When I force this package to 3.2.0 instead, the application runs correctly.

I'll publish this workaround immediately!

**Comment by Tarmil** [comment]
This fix is published as 0.14.14. To update the template:

    dotnet new -i Bolero.Templates::0.14.14

**Comment by janusschmidt** [comment]
No that doesn't change anything. Just tried, same error.
That change also is in the client. It is the server that gives me problems. The server needs the dependencies added to avoid runtime errors.

**Comment by Tarmil** [comment]
Okay, so your issue is indeed a different one @janusschmidt, thanks for confirming.

**Comment by rbrus** [comment]
I have tested it few days ago and it is not related. The other issue I wrote about prevented whole page to be displayed / render. Simply the page is stuck in loading.... Whereas this issue is only visible in the console and (might) prevents some actions (don't remember which one exactly but I think there was something), but the whole page will be displayed and render.
