### ISSUE TITLE
Using --paket when paket is not installed as a global tool results in an error...

### ISSUE THREAD

**Issue by Arshia001** [fsbolero/Template#26]
that looks like this:

```
Running command 'dotnet paket convert-from-nuget --force'...
Command failed.
Output from command:
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-paket does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

This can easily be fixed by altering the template to install paket as a local tool inside the solution (i.e. .config/dotnet-tools.json); which is also a better choice than globally installed tools in general. I don't know how dotnet templates work or I'd submit a PR.

**Comment by Arshia001** [comment]
Looking through the source, there already seems to be a `.config/dotnet-tools.json` in the template? I just installed the latest template from nuget, what am I missing?

**Comment by OnurGumus** [comment]
I am having a similar issue.
