### ISSUE TITLE
I can't run Client only Project

### ISSUE THREAD

**Issue by Oryan-Hassidim** [fsbolero/Template#31]
When I create project with:
`dotnet new bolero-app --server=false`
I can't run my webAssembly.
can I get Help??🙃
Oryan.Hassidim@gmail.com

**Comment by Tarmil** [comment]
Oh, I think I see what the problem is. In the latest dotnet project template, the file `index.html` is mistakenly not created when `server=false`. I'll fix this right away!

**Comment by Oryan-Hassidim** [comment]
😄😄
Thanks!!!!
Can you notify me when it's updated?

בתאריך יום ב׳, 31 במאי 2021, 21:24, מאת Loïc Denuzière ‏<
***@***.***>:

**Comment by Tarmil** [comment]
@Oryan-Hassidim Sorry it took so long, but it's finally out!

```
dotnet new -i Bolero.Templates::0.17.11
```
