### ISSUE TITLE
Bolero.Build.BoleroTask task could not be loaded

### ISSUE THREAD

**Issue by weebs** [fsbolero/Template#4]
Running the following leaves me with this error

> dotnet new -i Bolero.Templates
> dotnet new bolero-app -o RemoteTest
> cd RemoteTest
> dotnet build

> C:\Users\Dave\.nuget\packages\bolero.build\0.2.110\build\Bolero.Build.targets(13,5): error MSB4062: The "Bolero.Build.BoleroTask" task could not be loaded from the assembly C:\Users\Dave\.nuget\packages\bolero.build\0.2.110\build\..\tools\Bolero.Build.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\Dave\Projects\RemoteTest\src\RemoteTest.Client\RemoteTest.Client.fsproj]

I previously had an older version installed, and am running on Windows 10

The project does actually seem to build & run fine however (with the above error being produced at the end of each dotnet build)

**Comment by Tarmil** [comment]
If you have worked on a Bolero 0.1 project before with no shutdown in-between, it's possible that dotnet is trying to reuse the same build process. Does this still happen after running `dotnet build-server shutdown`?

**Comment by weebs** [comment]
Thanks! Running that command fixed the issue (and so did rebooting my machine).

**Comment by ctaggart** [comment]
This looks like it can be closed.
