### ISSUE TITLE
mismatch between project path created and used in solution file

### ISSUE THREAD

**Issue by ajeckmans** [fsbolero/Template#41]
I just created a folder with dashes in it on **linux** named `some-name`. Then ran `dotnet new bolero-app`. The solution file created contained the following:
```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "src", "src", "{87F6C079-CBD7-4866-BDEB-CBDEA9E51D2A}"
EndProject
Project("{6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705}") = "some_name.Server", "src\some_name.Server\some_name.Server.fsproj", "{4E2AA925-4694-4593-ADBC-F349D269587A}"
EndProject
Project("{6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705}") = "some_name.Client", "src\some_name.Client\some_name.Client.fsproj", "{1481BBD6-A6DA-4912-A03A-134880D14701}"
EndProject
```
on disk this file structure was created:

```
some-name.Client.sln
src/some-name.Client/some-name.Client.fsproj
src/some-name.Server/some-name.Server.fsproj
```

Note the backslash instead of forward slash and the underscore instead of hyphen inside the solution file.

**Comment by sledorze** [comment]
Same experience on Mac

**Comment by Tarmil** [comment]
The underscore instead of dash is indeed a problem, I'll push a fix for it soon.

Backslashes in project and solution files are fine, MSBuild can translate them to the native path separator for your OS.

**Comment by sledorze** [comment]
Thanks a lot!
