### ISSUE TITLE
Why is camelCasing being used for the record fields in the Elmish model?

### ISSUE THREAD

**Issue by ghost** [fsbolero/Template#49]
I have just started playing around with Belero and immediately, I noticed that the Model in the no-server template uses camelCasing for its records. Is there any particular reason for this? Please see the snippet of code below.

```.fs
/// The Elmish application's model.
type Model =
    {
        page: Page
        counter: int
        books: Book[] option
        error: string option
    }

and Book =
    {
        title: string
        author: string
        publishDate: DateTime
        isbn: string
    }

let initModel =
    {
        page = Home
        counter = 0
        books = None
        error = None
    }
```

**Comment by Tarmil** [comment]
There is no universally accepted standard for F# record field names; some people use camelCase, and others prefer PascalCase. Feel free to rename them in your project if you want!
